{
  self,
  lib,
  config,
  pkgs,
  ...
}:
let
  port = 6167;
  domain = "matrix.internetfeno.men";

  defaultAppserviceConfig = {
    homeserver = {
      address = "http://127.0.0.1:${toString port}";
      inherit domain;
    };
    encryption = {
      allow = true;
      default = true;
      require = true;
      pickle_key = "$PICKLE_KEY";
      appservice = false;
      self_sign = true;
      delete_keys = {
        dont_store_outbound = true;
        ratchet_on_decrypt = true;
        delete_fully_used_on_decrypt = true;
        delete_prev_on_new_session = true;
        delete_on_device_delete = true;
        periodically_delete_expired = true;
        delete_outdated_inbound = true;
      };
    };
    bridge = {
      permissions = {
        "*" = "relay";
        "matrix.org" = "user";
        "${domain}" = "user";
        "@ankarhem:${domain}" = "admin";
        "@admin:${domain}" = "admin";
      };
    };
    # new syntax for login_shared_secret_map
    double_puppet = {
      servers = { };
      allow_discovery = false;
      secrets."${domain}" = "as_token:$DOUBLEPUPPET_AS_TOKEN";
    };
    backfill = {
      enabled = true;
      max_initial_messages = 50;
      max_catchup_messages = 500;
      # unread_hours_threshold = 720;
    };
  };
in
{
  # Nginx
  services.nginx.virtualHosts."${domain}" = {
    forceSSL = true;
    useACMEHost = "internetfeno.men";

    extraConfig = ''
      listen 8448 ssl http2 default_server;
      client_max_body_size 500M;
    '';
    locations."/" = {
      proxyPass = "http://127.0.0.1:${toString port}";
    };
  };

  sops.secrets."tuwunel/registration_token" = {
    owner = "tuwunel";
  };
  services.matrix-tuwunel = {
    enable = true;
    package = pkgs._unstable.matrix-tuwunel;

    stateDirectory = "tuwunel";
    settings = {
      global = {
        address = [ "127.0.0.1" ];
        port = [ port ];
        server_name = domain;

        # Federation
        well_known = {
          server = "${domain}:443";
          client = "https://${domain}";
        };
        trusted_servers = [
          "matrix.org"
        ];
        # unix_socket_path = "/run/tuwunel/tuwunel.sock";
        # unix_socket_perms = 660;

        # Registration
        allow_registration = true;
        new_user_displayname_suffix = "👋";
        registration_token_file = config.sops.secrets."tuwunel/registration_token".path;
        forbidden_usernames = [
          "administrator"
          "admin"
        ];

        # Features
        allow_encryption = true;
        allow_federation = true;
        max_request_size = 104857600; # ~100 MB
        require_auth_for_profile_requests = true;
        suppress_push_when_active = true;

        # Backups
        database_backup_path = "/mnt/DISKETTEN_drive/tuwunel/backups";

        # Appservices: registrations are generated by the bridges
        # (mautrix-meta-*-registration.service, mautrix-signal pre-start) and
        # symlinked into this directory by tmpfiles. Tokens are owned by the
        # bridges; doublepuppet is rendered from sops.
        # NOTE: deliberately NOT under /var/lib/tuwunel — that is a DynamicUser
        # private state dir (symlink into /var/lib/private, owned nobody:nogroup
        # 0700): systemd-tmpfiles refuses "unsafe path transitions" there and
        # the service cannot traverse it either.
        appservice_dir = "/var/lib/tuwunel-appservices";
      };
    };
  };

  # Appservice registration files must exist before tuwunel starts
  systemd.services.tuwunel = {
    wants = [
      "mautrix-meta-instagram-registration.service"
      "mautrix-meta-messenger-registration.service"
      "mautrix-signal.service"
    ];
    after = [
      "mautrix-meta-instagram-registration.service"
      "mautrix-meta-messenger-registration.service"
      "mautrix-signal.service"
    ];
    # Registration files are 640 root:mautrix-meta-registration / root:mautrix-signal,
    # but the meta data directories are 0750 root:mautrix-meta — traversal needs
    # that group too (StateDirectory re-asserts it on every unit start).
    serviceConfig.SupplementaryGroups = [
      "mautrix-meta"
      "mautrix-meta-registration"
      "mautrix-signal"
    ];
  };

  systemd.tmpfiles.rules = [
    # Plain root-owned dir (outside the DynamicUser private state dir) —
    # 0755 is fine: it only contains symlinks; the target files carry their
    # own restrictive permissions.
    "d /var/lib/tuwunel-appservices 0755 root root - -"
    "L /var/lib/tuwunel-appservices/instagram.yaml - - - - /var/lib/mautrix-meta-instagram/meta-registration.yaml"
    "L /var/lib/tuwunel-appservices/messenger.yaml - - - - /var/lib/mautrix-meta-messenger/meta-registration.yaml"
    "L /var/lib/tuwunel-appservices/signal.yaml - - - - /var/lib/mautrix-signal/signal-registration.yaml"
    "L /var/lib/tuwunel-appservices/doublepuppet.yaml - - - - ${
      config.sops.templates."tuwunel-appservices/doublepuppet.yaml".path
    }"
  ];

  sops.secrets."matrix/doublepuppet_as_token" = { };
  sops.secrets."matrix/doublepuppet_hs_token" = { };
  sops.secrets."matrix/pickle_key" = { };

  # Double-puppeting appservice registration (receive-only). Mirrors the
  # mautrix double-puppeting recipe: url null, rate_limited false,
  # @.*:<server> namespace NON-exclusive so it doesn't take over all users.
  # as_token must match what the bridges receive via $DOUBLEPUPPET_AS_TOKEN.
  # hs_token is inert (url is null) but kept in sops so no credential-shaped
  # value lives in the repo.
  sops.templates."tuwunel-appservices/doublepuppet.yaml" = {
    owner = "tuwunel";
    content = ''
      id: doublepuppet
      url: null
      as_token: ${config.sops.placeholder."matrix/doublepuppet_as_token"}
      hs_token: ${config.sops.placeholder."matrix/doublepuppet_hs_token"}
      sender_localpart: doublepuppet
      rate_limited: false
      namespaces:
        users:
          - regex: "@.*:matrix.internetfeno.men"
            exclusive: false
    '';
  };

  # Appservice tokens are no longer injected: the bridges own their tokens
  # via their generated registration files in /var/lib/*/…-registration.yaml.
  sops.templates."mautrix-bridges.env" = {
    content = ''
      DOUBLEPUPPET_AS_TOKEN=${config.sops.placeholder."matrix/doublepuppet_as_token"}
      PICKLE_KEY=${config.sops.placeholder."matrix/pickle_key"}
    '';
  };

  # temporary allow olm-3.2.16 as insecure package
  nixpkgs.config.permittedInsecurePackages = [
    "olm-3.2.16"
  ];
  services.mautrix-meta = {
    instances = {
      instagram = {
        enable = true;
        environmentFile = config.sops.templates."mautrix-bridges.env".path;
        settings = lib.recursiveUpdate defaultAppserviceConfig {
          network.mode = "instagram";
          appservice = {
            id = "instagrambot";
            bot = {
              username = "instagrambot";
              displayname = "Instagram bridge bot";
            };
          };
        };
      };
      messenger = {
        enable = true;
        environmentFile = config.sops.templates."mautrix-bridges.env".path;
        settings = lib.recursiveUpdate defaultAppserviceConfig {
          network.mode = "messenger";
          appservice = {
            id = "messengerbot";
            # Existing ghosts are @meta_*: pin the template so the upgraded
            # bridge (v26.07) does not switch to a different default prefix.
            username_template = "meta_{{.}}";
            bot = {
              username = "messengerbot";
              displayname = "Messenger bridge bot";
            };
          };
        };
      };
    };
  };

  services.mautrix-signal = {
    enable = true;
    environmentFile = config.sops.templates."mautrix-bridges.env".path;
    settings = lib.recursiveUpdate defaultAppserviceConfig {
      appservice = {
        id = "signalbot";
        bot = {
          username = "signalbot";
          displayname = "Signal bridge bot";
        };
      };
    };
  };
}
